language: dart

dart:
  - stable
  - dev

jobs:
  include:
  - stage: lint
    dart: stable
    script:
      - dartanalyzer --fatal-infos --fatal-warnings .

  - stage: deploy docs
    branches:
      only:
        - master
    dart: stable
    script:
      - dartdoc
    deploy:
      provider: pages
      local-dir: doc/api
      skip-cleanup: true
      github-token: $GITHUB_TOKEN
      name: flyingB0tat0
      email: bot@baudisch.xyz
      keep-history: false
      allow-empty-commit: true
