name: libvplan
version: 0.1.0
description: A client and parser for indiware timetable changes.

environment:
  sdk: '>=2.0.0'

dependencies:
  http: ^0.12.0
  intl: ^0.15.7
  path: ^1.6.2
  test: ^1.5.1
  xml: ^3.2.3
